server:
  port: 3002
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaoxiufei/runoob
          search-paths: runoob-cloud/runoob-cloud-config/**
          default-label: master
          clone-on-start: true
# 高可用 配置服务注册中心
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/