spring:
  application:
    name: eureka-server
server:
  port: 1002

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    # 高可用 配置服务注册中心
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    register-with-eureka: false
    fetch-registry: false
