server:
  port: 3001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaoxiufei/runoob
          search-paths: runoob-cloud/runoob-cloud-config
          default-label: master
          clone-on-start: true
          username:
          password:
management:
  security:
    enabled: false
# 高可用 配置服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/