spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaoxiufei/runoob/tree/master/runoob-cloud/runoob-cloud-config/
          username:
          password:
server:
  port: 3001