server:
  port: 5001
spring:
  application:
    name: zuul-gateway
# 高可用 配置服务注册中心
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 10
    #告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/
#对于面向服务的路由配置，
#除了使用path与serviceId映射的配置方式之外，
#还有一种更简洁的配置方式：zuul.routes.<serviceId>=<path>，
#其中<serviceId>用来指定路由的具体服务名，<path>用来配置匹配的请求表达式。
#比如下面的例子，它的路由规则等价于上面通过path与serviceId组合使用的配置方式。
#默认：http://localhost:5001/dm-provider/service
#默认：http://localhost:5001/open-api/query
#配置：http://localhost:5001/abc/service
#配置：http://localhost:5001/def/query
#
zuul:
  routes:
    dm-provider: /abc/**
    open-api: /open/**

management:
  security:
    enabled: false
